baseurl = "https://leoh0.github.io/" # Controls base URL sitewide
languageCode = "en-US" # Controls site language
title = "> /dev/null" # Homepage title and page title suffix
paginate = 11 # Number of posts to show before paginating

# Controls default theme and theme components
theme = [
  "hermit"
]

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "UA-46519012-1" # Optional, add tracking Id for analytics
disqusShortname = "leoh0githubio" # Optional, add Disqus shortname for comments
SectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

pygmentsstyle = "api"

keywords = [
  "kubernetes",
  "openstack",
  "infrastructure"
]

[menu]

  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"

  [[menu.main]]
    name = "Posts"
    weight = 2
    identifier = "post"
    url = "/post/"

  [[menu.main]]
    name = "AboutMe"
    weight = 3
    identifier = "about"
    url = "/about/aboutme"

  [[menu.main]]
    name = "."
    weight = 100
    identifier = "blog"
    url = "/blog/"

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
    name = "keywords"
    weight = 150

  [[related.indices]]
    name  = "tags"
    weight = 100

  [[related.indices]]
    name  = "date"
    weight = 10
    pattern = "2006"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitle = "... nothing ..."

  justifyContent = false

  description = "... nothing ..." # Suggested, controls default description meta
  author = "leoh0" # Optional, controls author name display on posts
  hide_author = false # Optional, set true to hide author name on posts
  show_menu = true # Optional, set true to enable section menu
  powered_by = false # Optional, set false to disable credits
  related_content_limit = 5
  toc = true

  images = [
    "https://source.unsplash.com/collection/983219/2000x1322"
  ] # Suggested, controls default Open Graph images

  #themeColor = "#494f5c"
  themeColor = "#111111"
