name: update-photo

on:
  schedule:
  - cron: '*/2 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install hugo
      run: sudo apt -y install hugo
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
